name: Bearer SAST Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Bearer SAST
        uses: bearer/bearer-action@v2
        with:
          path: '.'
          format: 'json'
          output: 'bearer-report.json'
          exit-code: '0'    # Don't fail workflow even if issues found

      - name: Upload Bearer SAST report
        uses: actions/upload-artifact@v3
        with:
          name: bearer-sast-report
          path: bearer-report.json
