name: Bearer SAST Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer SAST Scan
        uses: bearer/bearer-action@v2
        with:
          path: '.'               # scan the entire repository
          format: 'tty'           # human-readable output in the Actions logs
          exit-code: '0'          # do not fail workflow if vulnerabilities found
          quiet: 'false'          # show progress and logs
