name: Bearer SAST Scan

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  rule_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Bearer SAST Scan
        uses: bearer/bearer-action@v2
        with:
          path: '.'
          format: 'json'            # Supported report format
          output: 'bearer-report.json'
          exit-code: '0'            # Do not fail workflow on findings
          quiet: 'false'            # Show logs in GitHub Actions
          hide-progress-bar: true

      - name: Upload Bearer report artifact
        uses: actions/upload-artifact@v3
        with:
          name: bearer-report
          path: bearer-report.json
