name: AppPy SAST Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: cycodelabs/cimon-action@v0  # 👈 Add Cimon first
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Step
        run: echo "Build completed."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: cycodelabs/cimon-action@v0  # 👈 Add Cimon first
      - name: Test Step
        run: echo "Tests executed."

  sast:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: cycodelabs/cimon-action@v0  # 👈 Add Cimon first
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Bandit SAST Scan
        run: |
          pip install bandit
          bandit app.py || true

  prod:
    runs-on: ubuntu-latest
    needs: sast
    steps:
      - uses: cycodelabs/cimon-action@v0  # 👈 Add Cimon first
      - name: Deploy Step
        run: echo "Deployed to production (simulated)"
