# Name of this GitHub Actions workflow.
name: Semgrep

on:
  pull_request: {}
  workflow_dispatch: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: '20 17 * * *'

permissions:
  contents: write  # Required to push report files to the repo.

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest

    container:
      image: semgrep/semgrep

    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v4

      - run: semgrep scan --config p/default --json --output semgrep-results.json

      - run: semgrep --json2html semgrep-results.json > semgrep-results.html

      # Optional: commit the results back to the repository (e.g., in a `semgrep-reports/` folder)
      - name: Commit Semgrep report files
        run: |
          mkdir -p semgrep-reports
          mv semgrep-results.* semgrep-reports/
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add semgrep-reports/
          git commit -m "Add Semgrep scan results [skip ci]" || echo "No changes to commit"
          git push
